# PostgreSQL. Versions 8.2 and up are supported.
#
# Install the pg driver:
#   gem install pg
# On OS X with Homebrew:
#   gem install pg -- --with-pg-config=/usr/local/bin/pg_config
# On OS X with MacPorts:
#   gem install pg -- --with-pg-config=/opt/local/lib/postgresql84/bin/pg_config
# On Windows:
#   gem install pg
#       Choose the win32 build.
#       Install PostgreSQL and put its /bin directory on your path.
#
# Configure Using Gemfile
# gem 'pg'
#

  # The specified database role being used to connect to postgres.
  # To create additional roles in postgres see `$ createuser --help`.
  # When left blank, postgres will use the default role. This is
  # the same name as the operating system user that initialized the database.

development:
  adapter: postgresql
  encoding: unicode
  database: railsnet-dev
  pool: 5
  host: localhost
  username: railsnet
  password: 123

test:
  adapter: postgresql
  encoding: unicode
  database: railsnet-test
  pool: 5
  host: localhost
  username: railsnet
  password: 123

production:
  adapter: postgresql
  encoding: unicode
  database: railsnet-prod
  pool: 5
  host: localhost
  username: railsnet
  password: 123